#!/bin/sh

echo "DEBUG DB_URL=$DB_URL"
echo "DEBUG SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL"

if [ -n "$DB_URL" ]; then
    export SPRING_DATASOURCE_URL="$DB_URL"
fi

echo "DEBUG FINAL SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL"

exec java $JAVA_OPTS -jar app.jar